"""empty message

Revision ID: c976fefe308c
Revises: 
Create Date: 2025-07-04 20:31:51.945225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c976fefe308c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('diario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('feliz', sa.Boolean(), nullable=True),
    sa.Column('triste', sa.Boolean(), nullable=True),
    sa.Column('alteracao_humor', sa.Boolean(), nullable=True),
    sa.Column('sensivel', sa.Boolean(), nullable=True),
    sa.Column('raiva', sa.Boolean(), nullable=True),
    sa.Column('irritavel', sa.Boolean(), nullable=True),
    sa.Column('ansiosa', sa.Boolean(), nullable=True),
    sa.Column('falta_controle', sa.Boolean(), nullable=True),
    sa.Column('indiferenca', sa.Boolean(), nullable=True),
    sa.Column('mente_confusa', sa.Boolean(), nullable=True),
    sa.Column('calma', sa.Boolean(), nullable=True),
    sa.Column('estresse', sa.Boolean(), nullable=True),
    sa.Column('motivacao', sa.Boolean(), nullable=True),
    sa.Column('criatividade', sa.Boolean(), nullable=True),
    sa.Column('bom_rendimento', sa.Boolean(), nullable=True),
    sa.Column('preguica_desanimo', sa.Boolean(), nullable=True),
    sa.Column('sociavel', sa.Boolean(), nullable=True),
    sa.Column('introvertida', sa.Boolean(), nullable=True),
    sa.Column('compreensiva', sa.Boolean(), nullable=True),
    sa.Column('amorosa', sa.Boolean(), nullable=True),
    sa.Column('conflituosa', sa.Boolean(), nullable=True),
    sa.Column('ferias', sa.Boolean(), nullable=True),
    sa.Column('encontros', sa.Boolean(), nullable=True),
    sa.Column('ressaca', sa.Boolean(), nullable=True),
    sa.Column('alcool', sa.Boolean(), nullable=True),
    sa.Column('cigarro', sa.Boolean(), nullable=True),
    sa.Column('dor_cabeca', sa.Boolean(), nullable=True),
    sa.Column('tensao_corporal', sa.Boolean(), nullable=True),
    sa.Column('dor_corporal', sa.Boolean(), nullable=True),
    sa.Column('insonia', sa.Boolean(), nullable=True),
    sa.Column('queda_cabelo', sa.Boolean(), nullable=True),
    sa.Column('taquicardia', sa.Boolean(), nullable=True),
    sa.Column('surto_acne', sa.Boolean(), nullable=True),
    sa.Column('sem_apetite', sa.Boolean(), nullable=True),
    sa.Column('alergia_dermatite', sa.Boolean(), nullable=True),
    sa.Column('gripe', sa.Boolean(), nullable=True),
    sa.Column('alteracao_hormonal', sa.Boolean(), nullable=True),
    sa.Column('problemas_digestivos', sa.Boolean(), nullable=True),
    sa.Column('palavras_carinho', sa.Boolean(), nullable=True),
    sa.Column('presentes', sa.Boolean(), nullable=True),
    sa.Column('xingamentos', sa.Boolean(), nullable=True),
    sa.Column('piadas_ofensivas', sa.Boolean(), nullable=True),
    sa.Column('mentira', sa.Boolean(), nullable=True),
    sa.Column('dar_gelo', sa.Boolean(), nullable=True),
    sa.Column('ciumes', sa.Boolean(), nullable=True),
    sa.Column('culpar', sa.Boolean(), nullable=True),
    sa.Column('proibir', sa.Boolean(), nullable=True),
    sa.Column('chantagem', sa.Boolean(), nullable=True),
    sa.Column('empurrar', sa.Boolean(), nullable=True),
    sa.Column('beliscar', sa.Boolean(), nullable=True),
    sa.Column('chutar', sa.Boolean(), nullable=True),
    sa.Column('apertar', sa.Boolean(), nullable=True),
    sa.Column('bater', sa.Boolean(), nullable=True),
    sa.Column('destruir_bens', sa.Boolean(), nullable=True),
    sa.Column('brincar_bater', sa.Boolean(), nullable=True),
    sa.Column('obrigou_relacao_sexual', sa.Boolean(), nullable=True),
    sa.Column('abuso_sexual', sa.Boolean(), nullable=True),
    sa.Column('confinar', sa.Boolean(), nullable=True),
    sa.Column('sufocar', sa.Boolean(), nullable=True),
    sa.Column('feriu_animal', sa.Boolean(), nullable=True),
    sa.Column('tentou_se_matar', sa.Boolean(), nullable=True),
    sa.Column('empurrar_outro', sa.Boolean(), nullable=True),
    sa.Column('beliscar_outro', sa.Boolean(), nullable=True),
    sa.Column('chutar_outro', sa.Boolean(), nullable=True),
    sa.Column('bater_outro', sa.Boolean(), nullable=True),
    sa.Column('ameacar', sa.Boolean(), nullable=True),
    sa.Column('apertar_outro', sa.Boolean(), nullable=True),
    sa.Column('pontuacao_total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
